site_name: IUEditor Beta Manual
pages:
  - ['index.md', 'Home']
  - ['Introduction/what-is-the-iueditor.md', '소개 Introduction', '아이유에디터가 뭐에요?']
  - ['Introduction/environment.md', '소개 Introduction', '구동환경은?']
  - ['Features/top-tool-bar.md', '기능설명 Features', '상단 툴바']
  - ['Features/structure-and-resource.md', '기능설명 Features', '페이지 스트럭쳐 & 리소스']
  - ['Features/middle-tool-bar.md', '기능설명 Features', '중앙 툴바']
  - ['Features/widget/box.md', '기능설명 Features', '중앙 툴바', '박스']  


theme: readthedocs
site_author: "iu@jdlab.org"
repo_url: https://github.com/IUEditor-Manual/iumanual.git


include_search : true
include_nav : true
include_next_prev : true
use_directory_urls : true