site_name: IUEditor Manual
pages:
  - ['index.md', 'Home']
  - ['Introduction/what-is-the-iueditor.md', '소개 Introduction', '아이유에디터가 뭐에요?']
  - ['Introduction/environment.md', '소개 Introduction', '구동환경은?']
  
  - ['Features/top-tool-bar.md', '기능설명 Features', '상단 툴바']
  - ['Features/structure-and-resource.md', '기능설명 Features', '페이지 스트럭쳐 & 리소스']
  - ['Features/middle-tool-bar.md', '기능설명 Features', '중앙 툴바']
  - ['Features/event-panel.md', '기능설명 Features', '이벤트 패널']
  
  - ['Widget/box.md', '위젯 Widgets', '박스']
  - ['Widget/text.md', '위젯 Widgets', '텍스트']
  - ['Widget/image.md', '위젯 Widgets', '이미지']
  - ['Widget/transition.md', '위젯 Widgets', '트랜지션']
  - ['Widget/carousel.md', '위젯 Widgets', '캐러젤']
  - ['Widget/webmovie.md', '위젯 Widgets', '웹무비']
  - ['Widget/video.md', '위젯 Widgets', '비디오클립']
  - ['Widget/import.md', '위젯 Widgets', '임포트']
  - ['Widget/tweet.md', '위젯 Widgets', '트윗 공유 버튼']
  - ['Widget/facebook.md', '위젯 Widgets', '페이스북 좋아요 버튼']
  - ['Widget/centeredbox.md', '위젯 Widgets', '센터박스']
  - ['Widget/form.md', '위젯 Widgets', '폼']
  - ['Widget/textfield.md', '위젯 Widgets', '텍스트필드']
  - ['Widget/textarea.md', '위젯 Widgets', '텍스트영역']
  - ['Widget/submit.md', '위젯 Widgets', '서브밋 버튼']
  - ['Widget/html.md', '위젯 Widgets', 'HTML']
    


theme: readthedocs
site_author: "iu@jdlab.org"
repo_url: https://github.com/IUEditor-Manual/iumanual.git


include_search : true
include_nav : true
include_next_prev : true
use_directory_urls : false
